<a href="https://colab.research.google.com/github/lenhattung/UnsupervisedLearning/blob/main/02-k_means_ex2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from sklearn.datasets import (
    load_iris
)

In [7]:
# Load dataset
iris = load_iris()
X = iris.data
y_true = iris.target

In [8]:

# Chỉ lấy 2 features để dễ vẽ
X_2d = X[:, [0, 2]]
# Sepal length và Petal length

In [9]:
# K-Means với k=3
kmeans = KMeans(
    n_clusters=3,
    random_state=42
)
y_pred = kmeans.fit_predict(X_2d)

In [10]:
from sklearn.metrics import (
 adjusted_rand_score
)

# Adjusted Rand Index
ari = adjusted_rand_score(
 y_true, y_pred
)
print(f"ARI: {ari:.3f}")

# Confusion matrix style
from sklearn.metrics import (
 confusion_matrix
)
cm = confusion_matrix(
 y_true, y_pred
)
print(cm)

ARI: 0.699
[[ 0 50  0]
 [ 4  1 45]
 [37  0 13]]
